[package]
name = "advent_of_codspeed"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
regex = "1.11.1"
wide = "0.7.30"

[dev-dependencies]
criterion = { package = "codspeed-criterion-compat", version = "*" }
